version: "3"

services:
  # PostgreSQL service
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    ports:
      - "5433:5432"

  # Go application service
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
